spring.application.name=site
spring.thymeleaf.cache=false
server.port=${PORT:8080}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=acerbis.leo@gmail.com
spring.mail.password=cixyskoktvxarkmw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true